services:
  app:
    image: 192.168.5.50:5000/progress:latest
    container_name: progress
    ports:
      - "5000:5000"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./claude_settings.json:/root/.claude/settings.json
      - ./codex_config.toml:/root/.codex/config.toml:ro
      - ./codex_auth.json:/root/.codex/auth.json:ro
      - ./data:/app/data

    environment:
      - PROGRESS_SCHEDULE_CRON=0 8 * * *

    restart: always
