"""Markdown 报告生成器"""

import logging
from datetime import datetime
from .analyzer import AnalysisResult

logger = logging.getLogger(__name__)


class MarkdownReporter:
    """生成 Markdown 格式的报告"""

    def generate_repository_report(
        self,
        repo_name: str,
        repo_url: str,
        branch: str,
        current_commit: str,
        previous_commit: str,
        commit_count: int,
        analysis: AnalysisResult,
        commit_messages: list[str]
    ) -> str:
        """生成单个仓库的 Markdown 报告（用于汇总）

        Returns:
            Markdown 内容
        """
        lines = [
            f"### 📦 {repo_name}\n",
            f"**仓库**: [{repo_url}](https://github.com/{repo_url})  ",
            f"**分支**: `{branch}`  ",
            f"**提交**: `{previous_commit[:8] if previous_commit else '初始'} → {current_commit[:8]}`  ",
            f"**数量**: {commit_count} 个提交\n",
        ]

        # 变更摘要
        if analysis.summary:
            lines.extend([
                f"**📝 变更摘要**: {analysis.summary}\n",
            ])
        else:
            lines.extend([
                "**📝 变更摘要**: 暂无详细摘要\n",
            ])

        # 提交消息
        if commit_messages:
            lines.append("**💬 提交消息**:")
            for msg in commit_messages:
                lines.append(f"  - {msg}")
            lines.append("")

        # 详细变更（使用折叠区块）
        details = []
        if analysis.added_structures:
            details.append("**➕ 新增数据结构**:")
            details.extend([f"  - {item}" for item in analysis.added_structures])
            details.append("")

        if analysis.removed_structures:
            details.append("**➖ 删除数据结构**:")
            details.extend([f"  - {item}" for item in analysis.removed_structures])
            details.append("")

        if analysis.added_functions:
            details.append("**✨ 新增函数/方法**:")
            details.extend([f"  - {item}" for item in analysis.added_functions])
            details.append("")

        if analysis.modified_functions:
            details.append("**🔄 修改的函数/方法**:")
            details.extend([f"  - {item}" for item in analysis.modified_functions])
            details.append("")

        if analysis.removed_functions:
            details.append("**❌ 删除的函数/方法**:")
            details.extend([f"  - {item}" for item in analysis.removed_functions])
            details.append("")

        if analysis.api_changes:
            details.append("**🔌 API 变更**:")
            details.extend([f"  - {item}" for item in analysis.api_changes])
            details.append("")

        if analysis.important_changes:
            details.append("**⚠️ 重要变更**:")
            details.extend([f"  - {item}" for item in analysis.important_changes])
            details.append("")

        if details:
            lines.extend([
                "<details>",
                "<summary>🔍 查看详细变更</summary>",
                "\n",
            ])
            lines.extend(details)
            lines.append("</details>\n")

        lines.append("---\n")

        return "\n".join(lines)

    def generate_aggregated_report(self, reports: list) -> str:
        """生成汇总报告

        Args:
            reports: 报告列表，每个报告包含 repo_name, content 等

        Returns:
            完整的汇总 Markdown 报告
        """
        lines = [
            "# 🚀 开源项目代码变更汇总报告\n",
            f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n",
            f"**监控项目数**: {len(reports)} 个\n",
            "---\n",
        ]

        for report in reports:
            lines.append(report['content'])

        lines.append("\n---\n")
        lines.append(f"\n*📊 Generated by Progress Tracker @ {datetime.now().isoformat()}*")

        return "\n".join(lines)

    def generate(
        self,
        repo_name: str,
        repo_url: str,
        branch: str,
        current_commit: str,
        previous_commit: str,
        commit_count: int,
        analysis: AnalysisResult,
        commit_messages: list[str]
    ) -> str:
        """生成 Markdown 报告（单个仓库完整版，已弃用）

        Returns:
            Markdown 内容
        """
        lines = [
            f"# 📊 {repo_name} 代码变更报告\n",
            f"**仓库**: {repo_url}",
            f"**分支**: {branch}",
            f"**时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**提交范围**: `{previous_commit or '初始'} → {current_commit[:8]}`",
            f"**提交数量**: {commit_count}\n",
            "---\n",

            "## 📝 变更摘要",
            analysis.summary or "暂无摘要",
            "\n---\n",

            "## 💬 提交消息",
        ]

        for msg in commit_messages:
            lines.append(f"- {msg}")

        lines.append("\n---\n")

        # 各类变更
        if analysis.added_structures:
            lines.extend([
                "## ➕ 新增数据结构",
                *self._format_list(analysis.added_structures),
                "\n"
            ])

        if analysis.removed_structures:
            lines.extend([
                "## ➖ 删除数据结构",
                *self._format_list(analysis.removed_structures),
                "\n"
            ])

        if analysis.added_functions:
            lines.extend([
                "## ✨ 新增函数/方法",
                *self._format_list(analysis.added_functions),
                "\n"
            ])

        if analysis.modified_functions:
            lines.extend([
                "## 🔄 修改的函数/方法",
                *self._format_list(analysis.modified_functions),
                "\n"
            ])

        if analysis.removed_functions:
            lines.extend([
                "## ❌ 删除的函数/方法",
                *self._format_list(analysis.removed_functions),
                "\n"
            ])

        if analysis.api_changes:
            lines.extend([
                "## 🔌 API 变更",
                *self._format_list(analysis.api_changes),
                "\n"
            ])

        if analysis.important_changes:
            lines.extend([
                "## ⚠️ 重要变更",
                *self._format_list(analysis.important_changes),
                "\n"
            ])

        lines.append("---\n")
        lines.append(f"\n*Generated by Progress Tracker @ {datetime.now().isoformat()}*")

        return "\n".join(lines)

    def _format_list(self, items: list[str]) -> list[str]:
        """格式化列表项"""
        return [f"- {item}" for item in items]

