#!/usr/bin/env python3
"""Export OpenAPI schema from the FastAPI app (spec 12).

Per spec 12, this script exports the OpenAPI schema to ``web/openapi.json``
which is committed as a contract artifact. CI uses this to detect schema drift
and generate TypeScript types for the frontend.

The file is part of the ``web/`` Prettier project, so the committed artifact is
Prettier-formatted (e.g. short arrays collapse onto one line). To stay
drift-free the raw ``json.dump`` output is piped through Prettier so the
generated bytes match the committed format exactly.

Usage:
    python scripts/export_openapi.py
"""

from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys

# Add src to path so we can import progress
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from progress.api import create_app

REPO_ROOT = Path(__file__).resolve().parent.parent
WEB_DIR = REPO_ROOT / "web"
PRETTIER_BIN = WEB_DIR / "node_modules" / ".bin" / "prettier"


def _format_with_prettier(path: Path) -> bool:
    """Format ``path`` in place with the web Prettier config.

    Prettier is run with ``web`` as the working directory so its
    ``prettier-plugin-tailwindcss`` resolves against ``web/node_modules``. Returns
    ``True`` on success, ``False`` if Prettier is unavailable (e.g. the web deps
    were not installed) — in that case the raw ``json.dump`` output is left as-is
    so the schema is still written.
    """
    if not PRETTIER_BIN.exists():
        print(
            "warning: prettier not found under web/node_modules; "
            "openapi.json left unformatted (run `pnpm --dir web install`)",
            file=sys.stderr,
        )
        return False
    result = subprocess.run(
        [str(PRETTIER_BIN), "--write", path.name],
        cwd=WEB_DIR,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stderr or result.stdout, file=sys.stderr)
        return False
    return True


def main() -> None:
    """Export OpenAPI schema to web/openapi.json."""
    app = create_app()
    schema = app.openapi()

    output_path = WEB_DIR / "openapi.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as f:
        json.dump(schema, f, indent=2, ensure_ascii=False)

    _format_with_prettier(output_path)

    print(f"OpenAPI schema exported to {output_path}")


if __name__ == "__main__":
    main()
