from __future__ import annotations

import json
import logging
from typing import Any, Mapping, NamedTuple

from ...i18n import gettext as _
from ..channels.feishu import FeishuChannel
from ..utils import (
    ChangelogEntry,
    DiscoveredRepo,
    NotificationType,
    add_batch_indicator,
    compute_notification_stats,
)
from .base import Message

logger = logging.getLogger(__name__)


class FeishuContext(NamedTuple):
    title: str
    summary: str
    total_commits: int
    markpost_url: str | None = None
    repo_statuses: Mapping[str, str] | None = None
    notification_type: NotificationType = "repo_update"
    changelog_entries: list[ChangelogEntry] | None = None
    discovered_repos: list[DiscoveredRepo] | None = None
    batch_index: int | None = None
    total_batches: int | None = None


class FeishuProposalContext(NamedTuple):
    title: str
    markpost_url: str | None = None
    filenames: list[str] | None = None
    more_count: int = 0


class FeishuMessage(Message):
    def __init__(self, channel: FeishuChannel) -> None:
        super().__init__(channel)
        logger.debug("FeishuMessage initialized")

    def get_payload(self, context: FeishuContext) -> str:
        title_with_batch = add_batch_indicator(
            context.title, context.batch_index, context.total_batches
        )
        card = self._build_card(context, title_with_batch)
        logger.debug("Prepared Feishu payload for %s", title_with_batch)
        return json.dumps(card, ensure_ascii=False)

    def _build_card(self, context: FeishuContext, title: str) -> dict[str, Any]:
        card: dict[str, Any] = {
            "header": self._build_header(title),
            "elements": self._build_elements(context),
        }
        if (
            context.notification_type in ("changelog", "discovered_repos")
            and context.markpost_url
        ):
            card["card_link"] = {"url": context.markpost_url}
        return card

    def _build_header(self, title: str) -> dict[str, Any]:
        return {
            "title": {"tag": "plain_text", "content": title},
            "template": "blue",
        }

    def _build_elements(self, context: FeishuContext) -> list[dict[str, Any]]:
        if context.notification_type == "changelog":
            return self._build_changelog_elements(context)
        if context.notification_type == "discovered_repos":
            return self._build_discovered_repos_elements(context)
        return self._build_default_elements(context)

    def _build_default_elements(self, context: FeishuContext) -> list[dict[str, Any]]:
        stats = compute_notification_stats(context.repo_statuses)
        elements: list[dict[str, Any]] = [
            self._build_overview_element(context.summary),
            {"tag": "hr"},
            self._build_stats_element(stats, total_commits=context.total_commits),
        ]

        failed_element = self._build_repo_list_element(
            title=_("Failed Repositories"),
            repos=stats.failed_repos,
        )
        if failed_element:
            elements.append(failed_element)

        skipped_element = self._build_repo_list_element(
            title=_("Skipped Repositories"),
            repos=stats.skipped_repos,
        )
        if skipped_element:
            elements.append(skipped_element)

        action_element = self._build_action_element(context.markpost_url)
        if action_element:
            elements.append(action_element)

        return elements

    def _build_changelog_elements(self, context: FeishuContext) -> list[dict[str, Any]]:
        elements: list[dict[str, Any]] = []
        entries = context.changelog_entries or []
        for idx, entry in enumerate(entries):
            name_and_version = f"{entry.name} {entry.version}".strip()
            elements.append(
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"• [{name_and_version}]({entry.url})",
                    },
                }
            )
            if idx < len(entries) - 1:
                elements.append({"tag": "hr"})

        if entries:
            elements.append({"tag": "hr"})
        elements.append(
            {
                "tag": "div",
                "text": {"tag": "lark_md", "content": "_Generated by Progress_"},
            }
        )
        return elements

    def _build_discovered_repos_elements(
        self, context: FeishuContext
    ) -> list[dict[str, Any]]:
        elements: list[dict[str, Any]] = []
        repos = context.discovered_repos or []
        visible = repos[:5]

        for idx, repo in enumerate(visible):
            elements.append(
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"[{repo.name}]({repo.url})",
                    },
                }
            )
            if idx < len(visible) - 1 or len(repos) > 5:
                elements.append({"tag": "hr"})

        if len(repos) > 5:
            elements.append(
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"... and {len(repos) - 5} more",
                    },
                }
            )
            elements.append({"tag": "hr"})

        elements.append(
            {
                "tag": "div",
                "text": {"tag": "lark_md", "content": "_Generated by Progress_"},
            }
        )
        return elements

    def _build_overview_element(self, summary: str) -> dict[str, Any]:
        overview_title = _("Overview")
        return {
            "tag": "div",
            "text": {
                "tag": "lark_md",
                "content": f"**{overview_title}**\n{summary}",
            },
        }

    def _build_stats_element(self, stats, total_commits: int) -> dict[str, Any]:
        return {
            "tag": "div",
            "fields": [
                self._build_stat_field(_("Total Repositories"), stats.total_repos),
                self._build_stat_field(_("Total Commits"), total_commits),
                self._build_stat_field(_("Successful"), stats.success_count),
                self._build_stat_field(_("Failed"), stats.failed_count),
            ],
        }

    def _build_stat_field(self, label: str, value: int) -> dict[str, Any]:
        return {
            "is_short": True,
            "text": {
                "tag": "lark_md",
                "content": f"**{label}**\n{value}",
            },
        }

    def _build_repo_list_element(
        self, title: str, repos: list[str]
    ) -> dict[str, Any] | None:
        if not repos:
            return None

        visible = repos[:5]
        content_lines = [f"- {name}" for name in visible]
        if len(repos) > len(visible):
            content_lines.append(f"- ... and {len(repos) - len(visible)} more")

        return {
            "tag": "div",
            "text": {
                "tag": "lark_md",
                "content": f"**{title}**\n" + "\n".join(content_lines),
            },
        }

    def _build_action_element(self, markpost_url: str | None) -> dict[str, Any] | None:
        if not markpost_url:
            return None
        return {
            "tag": "action",
            "actions": [
                {
                    "tag": "button",
                    "text": {"tag": "plain_text", "content": _("View Detailed Report")},
                    "type": "default",
                    "url": markpost_url,
                }
            ],
        }


class FeishuProposalMessage(Message):
    def __init__(self, channel: FeishuChannel) -> None:
        super().__init__(channel)

    def get_payload(self, context: FeishuProposalContext) -> str:
        elements: list[dict[str, Any]] = []
        filenames = context.filenames or []
        for idx, fname in enumerate(filenames):
            elements.append(
                {"tag": "div", "text": {"tag": "lark_md", "content": f"📄 {fname}"}}
            )
            if idx < len(filenames) - 1 or context.more_count > 0:
                elements.append({"tag": "hr"})
        if context.more_count > 0:
            elements.append(
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"... and {context.more_count} more",
                    },
                }
            )

        card: dict[str, Any] = {
            "header": {
                "template": "blue",
                "title": {"tag": "plain_text", "content": context.title},
            },
            "elements": elements,
        }
        if context.markpost_url:
            card["card_link"] = {"url": context.markpost_url}
        logger.debug("Prepared Feishu proposal payload for %s", context.title)
        return json.dumps(card, ensure_ascii=False)
